In [8]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


In [13]:
# Step 1: Load the dataset
print("Step 1: Load the Dataset")
df = pd.read_csv('Social_Network_Ads.csv')
# Display the first few rows of the dataset
print(df.head())
print("\n")

Step 1: Load the Dataset
    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0




In [12]:
# Step 2: Preprocess the data
print("Step 2: Preprocess the Data")
# Checking for any missing values
missing_values = df.isnull().sum()
print(f"Missing values in each column:\n{missing_values}\n")

# Splitting data into features (X) and target (y)
X = df[['Age', 'EstimatedSalary']].values  # Features: Age and Estimated Salary
y = df['Purchased'].values  # Target variable: Purchased (1 or 0)

print("Feature data (X):")
print(X[:5])  # First 5 rows of feature data
print("\nTarget data (y):")
print(y[:5])  # First 5 rows of target data
print("\n")

Step 2: Preprocess the Data
Missing values in each column:
User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

Feature data (X):
[[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]]

Target data (y):
[0 0 0 0 0]




In [14]:
# Step 3: Splitting data into training and test sets
print("Step 3: Splitting data into training and test sets")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

print(f"Training data size: {X_train.shape[0]} samples")
print(f"Test data size: {X_test.shape[0]} samples\n")


Step 3: Splitting data into training and test sets
Training data size: 300 samples
Test data size: 100 samples



In [15]:
# Step 4: Train the Logistic Regression model
print("Step 4: Train the Logistic Regression Model")
model = LogisticRegression()
model.fit(X_train, y_train)
print("Model trained successfully!\n")

Step 4: Train the Logistic Regression Model
Model trained successfully!



In [16]:
# Step 5: Make predictions
print("Step 5: Make Predictions")
y_pred = model.predict(X_test)

Step 5: Make Predictions


In [17]:
# Step 6: Compute confusion matrix
print("Step 6: Compute Confusion Matrix")
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)
print("\n")

Step 6: Compute Confusion Matrix
Confusion Matrix:
[[61  2]
 [10 27]]




In [19]:
# Step 7: Compute accuracy, error rate, precision, and recall
print("Step 7: Compute Performance Metrics")

# Calculate accuracy, error rate, precision, recall, and F1-score
accuracy = accuracy_score(y_test, y_pred)  # Proportion of correctly classified samples
error_rate = 1 - accuracy  # Proportion of misclassified samples
precision = precision_score(y_test, y_pred)  # Proportion of true positives among all predicted positives
recall = recall_score(y_test, y_pred)  # Proportion of true positives among all actual positives
f1 = f1_score(y_test, y_pred)  # Harmonic mean of precision and recall

print(f"Accuracy: {accuracy:.4f}")
print(f"Error Rate: {error_rate:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")


Step 7: Compute Performance Metrics
Accuracy: 0.8800
Error Rate: 0.1200
Precision: 0.9310
Recall: 0.7297
F1-Score: 0.8182
